name: Format

on:
  pull_request:
    branches: [ main ]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format-17
      - name: Check formatting
        run: |
          files=$(git ls-files '*.cpp' '*.hpp' '*.h' '*.cxx')
          clang-format-17 --dry-run --Werror $files
